require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ImportDataController do

  # This should return the minimal set of attributes required to create a valid
  # ImportDatum. As you add validations to ImportDatum, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ImportDataController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all import_data as @import_data" do
      import_datum = ImportDatum.create! valid_attributes
      get :index, {}, valid_session
      assigns(:import_data).should eq([import_datum])
    end
  end

  describe "GET show" do
    it "assigns the requested import_datum as @import_datum" do
      import_datum = ImportDatum.create! valid_attributes
      get :show, {:id => import_datum.to_param}, valid_session
      assigns(:import_datum).should eq(import_datum)
    end
  end

  describe "GET new" do
    it "assigns a new import_datum as @import_datum" do
      get :new, {}, valid_session
      assigns(:import_datum).should be_a_new(ImportDatum)
    end
  end

  describe "GET edit" do
    it "assigns the requested import_datum as @import_datum" do
      import_datum = ImportDatum.create! valid_attributes
      get :edit, {:id => import_datum.to_param}, valid_session
      assigns(:import_datum).should eq(import_datum)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ImportDatum" do
        expect {
          post :create, {:import_datum => valid_attributes}, valid_session
        }.to change(ImportDatum, :count).by(1)
      end

      it "assigns a newly created import_datum as @import_datum" do
        post :create, {:import_datum => valid_attributes}, valid_session
        assigns(:import_datum).should be_a(ImportDatum)
        assigns(:import_datum).should be_persisted
      end

      it "redirects to the created import_datum" do
        post :create, {:import_datum => valid_attributes}, valid_session
        response.should redirect_to(ImportDatum.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved import_datum as @import_datum" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportDatum.any_instance.stub(:save).and_return(false)
        post :create, {:import_datum => {}}, valid_session
        assigns(:import_datum).should be_a_new(ImportDatum)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ImportDatum.any_instance.stub(:save).and_return(false)
        post :create, {:import_datum => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested import_datum" do
        import_datum = ImportDatum.create! valid_attributes
        # Assuming there are no other import_data in the database, this
        # specifies that the ImportDatum created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ImportDatum.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => import_datum.to_param, :import_datum => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested import_datum as @import_datum" do
        import_datum = ImportDatum.create! valid_attributes
        put :update, {:id => import_datum.to_param, :import_datum => valid_attributes}, valid_session
        assigns(:import_datum).should eq(import_datum)
      end

      it "redirects to the import_datum" do
        import_datum = ImportDatum.create! valid_attributes
        put :update, {:id => import_datum.to_param, :import_datum => valid_attributes}, valid_session
        response.should redirect_to(import_datum)
      end
    end

    describe "with invalid params" do
      it "assigns the import_datum as @import_datum" do
        import_datum = ImportDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => import_datum.to_param, :import_datum => {}}, valid_session
        assigns(:import_datum).should eq(import_datum)
      end

      it "re-renders the 'edit' template" do
        import_datum = ImportDatum.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ImportDatum.any_instance.stub(:save).and_return(false)
        put :update, {:id => import_datum.to_param, :import_datum => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested import_datum" do
      import_datum = ImportDatum.create! valid_attributes
      expect {
        delete :destroy, {:id => import_datum.to_param}, valid_session
      }.to change(ImportDatum, :count).by(-1)
    end

    it "redirects to the import_data list" do
      import_datum = ImportDatum.create! valid_attributes
      delete :destroy, {:id => import_datum.to_param}, valid_session
      response.should redirect_to(import_data_url)
    end
  end

end
